name: Deploy to helm

on:
  workflow_call:
    inputs:
      cloud_provider:
        type: string
        default: "gcp"
        description: "Cloud provider (gcp, aws, azure)"

      helm_operation:
        default: "upgrade"
        description: "Helm operation"
        type: string
      helm_chart_name:
        type: string
        default: "dial"
        description: "Helm chart name"
      helm_chart_version:
        type: string
        default: "3.2.0"
        description: "Helm chart version"
      helm_values_file:
        type: string
        description: "Helm values file"
      helm_values:
        type: string
        description: "Helm values file"
      helm_release_name:
        type: string
        description: "Helm release name"
        default: "dial"
      helm_repo_name:
        type: string
        description: "Helm repository name"
        default: "dial"
      helm_repo_url:
        type: string
        description: "Helm repository URL"
        default: "https://charts.epam-rail.com"
      helm_extra_args:
        type: string
        description: "Extra arguments for Helm command"
        default: ""

      gcp_project_id:
        type: string
        default: "hl2-epm-dial-test-t1iylu"
        description: "Google project ID"
      gcp_workload_identity_provider:
        type: string
        default: "projects/771246914069/locations/global/workloadIdentityPools/ab-test-github-actions/providers/test-github-actions-oidc"
        description: "Google workload identity provider"
      gcp_service_account:
        type: string
        description: "Google service_account"
        default: "ab-test-github-actions@hl2-epm-dial-test-t1iylu.iam.gserviceaccount.com"
      gcp_location:
        type: string
        description: "Google artifact location"
        default: "us-central1"

      k8s_cluster_name:
        type: string
        default: "test"
        description: "K8s cluster name"
      k8s_namespace:
        type: string
        default: "default"
        description: "Kubernetes namespace to deploy into"

jobs:
  helm_update:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          lfs: true
      - id: install
        name: Install helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: "v3.13.3"
      - name: Install kubectl
        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v4.0.0
        with:
           version: 'v1.30.6'
      - id: "auth"
        name: Authenticate to Google Cloud
        if: ${{ inputs.cloud_provider == 'gcp' }}
        uses: google-github-actions/auth@8254fb75a33b976a221574d287e93919e6a36f70 # v2.1.6
        with:
          project_id: ${{ inputs.gcp_project_id }}
          workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
          service_account: ${{ inputs.gcp_service_account }}
      - id: "get-credentials"
        if: ${{ inputs.cloud_provider == 'gcp' }}
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: ${{ inputs.k8s_cluster_name }}
          location: ${{ inputs.gcp_location }}

      - name: Add Helm repository
        if: ${{ inputs.helm_operation  == 'upgrade' }}
        run: |
          helm repo add ${{ inputs.helm_repo_name }} ${{ inputs.helm_repo_url }}
           helm repo update

      - name: Upgrade Helm Chart
        if: ${{ inputs.helm_operation  == 'upgrade' }}
        env:
          HELM_VALUES_FILE: ${{ inputs.helm_values_file }}
          HELM_VALUES: ${{ inputs.helm_values }}
        run: |
          helm upgrade ${{ inputs.helm_release_name }} ${{ inputs.helm_repo_name }}/${{ inputs.helm_release_name }} \
            --version ${{ inputs.helm_chart_version }} \
            --namespace  ${{ inputs.k8s_namespace }} \
            --install --create-namespace --wait ${HELM_VALUES_FILE:+--values "$HELM_VALUES_FILE"} ${HELM_VALUES:+--set "$HELM_VALUES"} \
            ${{ inputs.helm_extra_args }}

      - name: Uninstall helm release
        if: ${{ inputs.helm_operation  == 'uninstall' }}
        run: |
          helm uninstall ${{ inputs.helm_release_name }} --namespace ${{ inputs.k8s_namespace }} \
            --ignore-not-found  \
            ${{ inputs.helm_extra_args }}

      - name: Delete k8s namespace
        if: ${{ inputs.helm_operation  == 'uninstall' }}
        run: |
          kubectl delete namespace ${{ inputs.k8s_namespace }} --ignore-not-found
